### ISSUE TITLE
✨ Crear GitHub Action para automatizar despliegue

### ISSUE THREAD

**Issue by adrgarcha** [adrgarcha/mariwano#77]
Crear un workflow de GitHub Actions que permita **desplegar automáticamente el proyecto en una instancia EC2** cada vez que se realice un `push` a la rama `main`, utilizando conexión por **SSH** para actualizar el código y ejecutar los comandos de despliegue en el servidor.

### 1. Preparar la instancia EC2

* Asegurar acceso por SSH.
* Tener `git` instalado.
* Clonar el repositorio por primera vez en el servidor:

```bash
cd /var/www
sudo mkdir -p app && sudo chown ubuntu:ubuntu app
cd app
git clone git@github.com:USUARIO/REPO.git .
```

---

### 2. Generar claves SSH para GitHub Actions

En local:

```bash
ssh-keygen -t ed25519 -C "github-actions-ec2" -f github_actions_ec2
```

* La **clave pública** se añadirá al archivo `~/.ssh/authorized_keys` del servidor EC2.
* La **clave privada** se guardará como secreto en GitHub.

---

### 3. Configurar secretos en GitHub

En el repositorio, añadir los siguientes secrets:

* `EC2_HOST` → IP o dominio de la instancia.
* `EC2_USER` → Usuario SSH.
* `EC2_SSH_KEY` → Contenido completo de la clave privada.

---

### 4. Crear el workflow de despliegue

Crear el archivo:

```
.github/workflows/ec2.yml
```

Contenido del workflow:

```yaml
name: Deploy to EC2 on main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd /var/www/app

            git fetch origin
            git reset --hard origin/main

            sudo docker build -t mariwano .
            sudo docker run mariwano

          EOF
```
